import os 
os. system("clear")
import time
    time.sleep(1)
    print("     Done....■□■□■□■□■□■□■□■□■□■!!")
    print("                        ")
    import os
    os. system("clear")
    print("  ___________________________________________________")
    print("  ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧")
    print("  ╢                ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄       ╟")
    print("  ╢                ████▌▄▌▄▐▐▌█████       ╟")
    print("  ╢                ████▌▄▌▄▐▐▌▀████       ╟")
    print("  ╢                ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀       ╟")
    print(f+"  ╢               ━━━━▣━━◤◢━━▣━━━━━    ╟")
    print(f+"  ╢           【ツ】   WELCOME  【ツ】             ╟")
    print("  ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤")
    print("  ╢                                                 ╟")
    print(f+"  ╢               Coded By: MENA MAGDY              ╟")
    print("  ╢                                                 ╟")
    print("  ╢____This tool is designed via Python language____╟")
    print("  ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤")
    print("  ╢________ Designed for Termux & Kali users________╟")
    print("  ╔╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤")
    print("  ╢__For more tools and explanations follow us on___╟")
    print("  ___________________________________________________")
    print(" ╢                                                   ╟")
    print(" ╢                YouTube channel:                   ╟")
    print(" ╢                                                   ╟")
    print(" ╢_____________https://youtu.be/iTaZJtXLeaE__________╟")
    print("  ___________________________________________________")
    print(" ╢                                                   ╟")
    print(" ╢                    TELEGRAM:                      ╟")
    print(" ╢                   JOIN US NOW                     ╟")
    print(" ╢   https://t.me/joinchat/NYmlVhPbCU9tfGxAeSaZ3A    ╟")
    print(" ╢                                                   ╟")
    print(" ╚╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧╤╧")
    print("THIS TOOL HAS BEEN PROGRAMED BY MENA MAGDY TO PENTRATION AND ECICAL HACKER")
    print("         MENA MAGDY = H⃟I⃟T⃟L⃟E⃟R⃟ H⃟A⃟C⃟K⃟ ")
    print("MY FACEBOOK ACC ➷➷➷➷➷ = MENA MAGDY ")
    print("  https://www.facebook.com/profile.php?id=100005415136153      ")
    print("MY YOUTUBE CANEL ")
    print("➷➷➷➷➷SUBSCRIBE NOW ➷➷➷➷➷")
    print("M3LOMAT THE PHONE = https://youtu.be/iTaZJtXLeaE    ")
    print("THIS TOOOL HAS BEEN PROGRAMED ONLY PYTHON L.N.G")
    print("MY ACC ON INSTAGRAM ==》 Mena.m.rushdy")
    print("i styding python & java & kotlin & ruby & bash ")
    print("AND SOCIAL ENGINEERING AND I STILL STUDING MOREE")
    print(" VERSTION : 1.2")
    print("╭━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━ ♥━")
    print("╰╮┏━┳┳┳┓  ┏┳┳┳┳┳┓  ┏┳┳┳┳┳┓")
    print("┏┻╋━╋┻┻┫  ┣┻┻┻┻┻┫  ┣┻┻┻┻┻┫")
    print("┗ⓞ━━━ⓞ┻━┻ⓞ━━ⓞ┻━┻ⓞ━━ⓞ╯")
    import time
    time.sleep(30)
    import os
